export const CARD_POOL: string[] = [
  'sushi', 'cold pizza at 2am', 'fresh bread from a bakery',
  'mac and cheese', 'a perfectly ripe avocado', 'street tacos', "grandma's cooking",
  'instant ramen at midnight', 'a charcuterie board',
  'breakfast for dinner', 'a really good takeaway',
  'a home-cooked meal', 'fancy restaurant leftovers',
  'chocolate chip cookies fresh from the oven', 'cinema popcorn',
  'a really good burrito', 'chips and guacamole', 'ice cream on a hot day',
  'waffles at midnight', 'airport food', 'wedding cake',
  'free office snacks', 'food truck tacos', 'all-you-can-eat buffet',
  'a perfect grilled cheese', 'soup on a cold day', 'birthday cake',
  'candy floss', 'drive-through at 2am',
  'napping on a rainy day', 'doomscrolling at 3am', 'karaoke',
  'people watching', 'binge-watching a new show', 'a long hot shower',
  'road trip with friends', 'sleeping in on Saturday', 'cooking a new recipe',
  'going to a concert', 'window shopping', 'doing absolutely nothing',
  'a spontaneous adventure', 'singing in the car', 'stargazing',
  'a lazy Sunday morning', 'board game night', 'building a pillow fort',
  'dancing in the kitchen', 'cloud watching', 'hammock napping',
  'thrift store shopping', 'a midnight walk', 'rewatching your comfort show',
  'a perfect high-five', 'late-night deep talks', 'a surprise day off',
  'beach day', 'snow day', 'first day of vacation',
  'staying up way too late', 'an unexpected compliment', 'a really good stretch',
  'pineapple on pizza', 'the movie was better than the book',
  'waking up early is underrated', 'cereal is a soup',
  'a hot dog is a sandwich', 'water is the best drink',
  'socks with sandals', 'replying-all to an email',
  'Monday mornings', 'small talk with strangers', 'the Oxford comma',
  'putting milk before cereal', 'double texting', 'leaving on read',
  'humble bragging', 'being fashionably late', 'dad jokes',
  'reality TV', 'auto-tune', 'Comic Sans font',
  'the snooze button', 'putting ketchup on everything',
  'parallel parking on the first try', 'talking to plants',
  'a really good pen', 'noise-cancelling headphones', 'a cozy blanket',
  'a brand new pair of socks', 'a fully charged phone', 'the TV remote',
  'a perfect pillow', 'sunglasses', 'a handwritten letter',
  'a library card', 'a Swiss Army knife', 'a reusable water bottle',
  'a good umbrella', 'wireless earbuds', 'a comfortable chair',
  'a sharp kitchen knife', 'a weighted blanket', 'chapstick',
  'a clean white t-shirt', 'a mechanical keyboard',
  'finding money in your pocket', 'a perfect parking spot',
  'the smell after rain', 'when your phone is at 100%',
  'cancelling plans', 'the first sip of coffee',
  'when the Wi-Fi connects instantly', 'getting a compliment from a stranger',
  'finishing a really good book', 'the feeling after a workout',
  'when your favorite song comes on shuffle', 'popping bubble wrap',
  'peeling the plastic off a new screen', 'the first bite of a meal',
  'waking up and realizing it\'s Saturday', 'a package arriving early',
  'green lights all the way home', 'exact change in your pocket',
  'the other side of the pillow', 'getting into a made bed',
  'a text from someone you miss', 'the last day of school',
  'catching something you dropped mid-air', 'no line at the grocery store',
  'a dog walking up to you', 'someone saving you a seat',
  'hearing someone laugh at your joke', 'stepping on a crunchy leaf',
  'remembering a dream', 'accidentally napping', 'a really good yawn',
  'hitting all green lights', 'the first warm day of spring',
  'a two-hour lunch break', 'an empty laundromat',
  'pizza delivery arriving early', 'guessing the time correctly',
  'time travel', 'teleportation', 'reading minds',
  'flying', 'invisibility', 'super strength',
  'speaking every language', 'photographic memory',
  'controlling the weather', 'talking to animals',
  'pausing time', 'unlimited money', 'perfect health forever',
  'a personal chef', 'a treehouse mansion', 'a time machine',
  'a magic carpet', 'a robot butler', 'a teleportation device',
  'a cloning machine', 'an unlimited gift card',
  'getting stuck in an elevator', 'awkward eye contact',
  'sending a text to the wrong person', 'waving at someone who wasn\'t waving at you',
  'your phone dying at 1%', 'stepping on a Lego',
  'forgetting someone\'s name immediately', 'walking into a glass door',
  'accidentally liking an old photo while stalking', 'a dead phone in an emergency',
  'losing your keys', 'running out of hot water mid-shower',
  'a cold toilet seat', 'biting your tongue', 'paper cuts',
  'tangled headphones', 'slow internet', 'no phone charger',
  'alarm not going off', 'wet socks', 'a warm toilet seat',
  'sitting in gum', 'mosquito bites', 'brain freeze',
  'traffic jams', 'a flat tire', 'sunburn',
  'being put on hold forever', 'a crowded elevator',
  'a squeaky shopping cart', 'forgetting why you walked into a room',
  'the friend who always cancels', 'reply-all nightmares',
  'Zoom meetings that could be emails', 'unread notifications',
  'low phone battery anxiety', 'choosing what to watch on Netflix',
  'the "we need to talk" text', 'parallel parking with an audience',
  'small talk in elevators', 'accidentally sending a half-typed message',
  'running into someone you know at the store', 'the airport security line',
  'a group project where you do all the work',
  'the person who microwaves fish at work',
  'holding the door for someone who is too far away',
  'forgetting your reusable bags at the store',
  'when someone says "we should hang out" but never plans it',
  'a friend who spoils movies', 'people who clap when the plane lands',
  'the coworker who always replies all',
  'loud chewing', 'backseat drivers',
  'people who stand on the left side of the escalator',
  'one-upping in conversations',
  'getting Rick Rolled', 'a plot twist in a movie',
  'the Wilhelm scream in movies', 'a mic drop moment',
  'an unexpected cameo', 'the post-credits scene',
  'winning a stuffed animal from a claw machine',
  'a snow globe collection', 'glow-in-the-dark stars on the ceiling',
  'a friendship bracelet', 'a mixtape from a friend',
  'the game-winning shot', 'a comeback victory',
  'a photo finish', 'an undefeated season',
  'a half-court shot', 'a hole in one',
  'a perfect bowling score', 'a last-minute equaliser',
  'learning to ride a bike', 'the first day at a new job',
  'your first apartment', 'graduation day',
  'a first kiss', 'a surprise birthday party',
  'meeting your best friend', 'your wedding day',
  'the birth of a child', 'retirement',
  'a standing ovation', 'winning the lottery',
  'going viral', 'meeting your hero',
  'the northern lights', 'a total solar eclipse',
  'bioluminescent waves', 'a double rainbow',
  'a shooting star', 'cliffs over the sea at sunset',
  'cherry blossoms in spring', 'the Milky Way on a clear night',
  'thunderstorms from a safe distance', 'autumn leaves changing color',
  'a perfectly brewed cup of tea', 'the smell of old books',
  'a vinyl record crackling', 'rain on a tin roof',
  'a fireplace on a winter night', 'the sound of waves crashing',
  'birds singing at dawn', 'a cat purring on your lap',
  'the smell of fresh laundry', 'a warm towel from the dryer',
  'cinnamon rolls fresh from the oven', 'the first snowfall of winter',
  'walking barefoot on grass', 'a perfectly skipped stone',
  'blowing out birthday candles', 'the crack of a baseball bat',
  'a campfire under the stars',
  'being the main character', 'living in a simulation',
  'parallel universes', 'the meaning of life',
  'whether fish have feelings', 'what dogs dream about',
  'if plants can hear music', 'life on other planets',
  'time being an illusion', 'the multiverse theory',
  'a world without internet', 'a world without gravity',
  'the best decade to live in', 'humanity in 1000 years',
  'the last human on Earth', 'a world where everyone can fly',
  'a world without money', 'a world without sleep',
  'being famous for a day', 'switching lives with someone for a week',
  'reliving your best day', 'knowing the future',
  'unlimited plane tickets', 'a year off with full pay',
  'the ability to cook anything perfectly', 'never having to clean again',
  'always having exact change', 'never getting stuck in traffic',
  'always finding a parking spot', 'clothes that never wrinkle',
  'a fridge that is always stocked', 'shoes that never wear out',
  'a self-cleaning house', 'never losing your keys',
  'always picking the fastest checkout line',
  'a playlist that always matches your mood',
  'remembering every name', 'never getting a hangover',
  'always knowing the right thing to say',
  'finishing every book you start',
  'morning person energy', 'night owl energy',
  'main character energy', 'golden retriever energy',
  'chaotic good energy', 'big brain energy',
  'cozy vibes', 'adventure vibes', 'nostalgia vibes',
  'summer camp vibes', 'road trip vibes', 'rainy day vibes',
  'Sunday morning vibes', 'Friday evening vibes',
  'back-to-school vibes', 'new year new me vibes',
  'vacation countdown vibes', 'last day of work vibes',
  'the friend who plans everything', 'the friend with the best stories',
  'the friend who is always late', 'the friend who remembers everything',
  'the friend who falls asleep first at sleepovers',
  'the friend who brings snacks',
  'a handshake that goes wrong', 'tripping on nothing',
  'saying goodbye then walking the same direction',
  'calling your teacher mom', 'your voice cracking at the worst time',
  'forgetting a word mid-sentence', 'walking the wrong way and having to turn around',
  'accidentally opening the front camera',
  'a text you wish you could unsend',
  'telling a joke nobody laughs at',
  'making eye contact through the bathroom stall crack',
];
